name: Publish

on:
  push:
    branches:
      - 'master'

permissions:
  pull-requests: write
  contents: write
  repository-projects: write
  packages: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Check if dist is up-to-date
        run: |
          if [[ $(git status --porcelain dist/) ]]; then
            echo "dist/ directory has uncommitted changes. Please build and commit the changes."
            git status --porcelain dist/
            exit 1
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "prod"
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false