name: Publish

on:
  push:
    branches:
      - 'master'

permissions:
  pull-requests: write
  contents: write
  repository-projects: write
  packages: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Check if dist is up-to-date
        id: check_dist
        run: |
          if [[ $(git status --porcelain dist/) ]]; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
        continue-on-error: true

      - name: Commit built files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add dist
          git commit -m "Update dist directory"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and Push New Tag
        run: |
          git tag -fa "prod" -m "Release prod"
          git push origin "prod" --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "prod"
          release_name: "Release prod"
          draft: false
          prerelease: false
